name: Deploy Nodejs Code on ExCloud

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v4
              with:
                  username: ${{ vars.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: QEMU
              uses: docker/setup-qemu-action@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v4

            - name: Docker Build and Push
              run: |
                  docker build -t craftwithsujeet/chaicode-node .
                  docker push craftwithsujeet/chaicode-node

            - name: Deploy on ExCloud
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: 210.79.129.216
                  username: ubuntu
                  key: ${{secrets.PRIVATE_KEY}}
                  script: |
                      export NVM_DIR="$HOME/.nvm"
                      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                      cd /home/ubuntu/chai-aur-deployment
                      git pull
                      npm install
                      pm2 restart 0
